// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'zh'

export type Locales =
	| 'en'
	| 'fr'
	| 'zh'
	| 'zh-TW'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	commands: {
		/**
		 * 打​开​目​录​侧​边​视​图
		 */
		openTocView: string
		/**
		 * 返​回​光​标​位​置
		 */
		returnToCursor: string
		/**
		 * 滚​动​到​顶​部
		 */
		scrollToTop: string
		/**
		 * 滚​动​到​底​部
		 */
		scrollToBottom: string
		/**
		 * 导​航​到​上​一​个​标​题
		 */
		navigatePreviousHeading: string
		/**
		 * 导​航​到​下​一​个​标​题
		 */
		navigateNextHeading: string
		/**
		 * 展​开​/​收​起​目​录
		 */
		tocExpand: string
		/**
		 * 插​入​阅​读​时​间​卡​片
		 */
		insertReadingTimeCard: string
		/**
		 * 插​入​目​录​卡​片
		 */
		insertTableOfContentsCard: string
		/**
		 * 添​加​/​移​除​当​前​文​件​到​标​题​编​号​黑​名​单
		 */
		addCurrentFileToHideHeadingNumberBlacklist: string
		/**
		 * 添​加​/​移​除​当​前​文​件​夹​到​标​题​编​号​黑​名​单
		 */
		addCurrentFolderToHideHeadingNumberBlacklist: string
	}
	notices: {
		/**
		 * 已​被​现​有​规​则​覆​盖
		 */
		alreadyCovered: string
		/**
		 * 已​添​加
		 */
		added: string
		/**
		 * 已​添​加​，​并​移​除​了​ ​{​c​o​u​n​t​}​ ​个​冗​余​规​则
		 * @param {number} count
		 */
		addedAndRemovedRedundant: RequiredParams<'count'>
		/**
		 * 不​在​黑​名​单​中
		 */
		notInBlacklist: string
		/**
		 * 已​移​除
		 */
		removed: string
		/**
		 * 已​被​某​个​规​则​覆​盖​，​如​需​移​除​请​手​动​删​除​该​规​则
		 */
		coveredByPattern: string
	}
	view: {
		/**
		 * 未​找​到​标​题​，​请​确​保​当​前​文​档​包​含​标​题​，​或​者​激​活​m​a​r​k​d​o​w​n​文​档​视​图​。
		 */
		view_empty: string
	}
	settings: {
		toc: {
			/**
			 * 目​录
			 */
			name: string
			show: {
				/**
				 * 显​示​目​录
				 */
				name: string
				/**
				 * 启​用​或​禁​用​目​录​功​能
				 */
				desc: string
			}
			alwaysExpand: {
				/**
				 * 始​终​展​开​目​录
				 */
				name: string
				/**
				 * 启​用​或​禁​用​始​终​展​开​目​录​，​可​使​用​文​档​属​性​ ​`​c​s​s​c​l​a​s​s​e​s​`​ ​来​控​制​显​示​与​隐​藏​：
				 */
				desc: string
			}
			width: {
				/**
				 * 目​录​宽​度
				 */
				name: string
				/**
				 * 设​置​目​录​的​宽​度
				 */
				desc: string
			}
			position: {
				/**
				 * 目​录​位​置
				 */
				name: string
				/**
				 * 设​置​目​录​的​位​置
				 */
				desc: string
				options: {
					/**
					 * 左​侧
					 */
					left: string
					/**
					 * 右​侧
					 */
					right: string
				}
			}
			offset: {
				/**
				 * 目​录​偏​移
				 */
				name: string
				/**
				 * 设​置​目​录​的​偏​移​量
				 */
				desc: string
			}
		}
		render: {
			/**
			 * 渲​染
			 */
			name: string
			useHeadingNumber: {
				/**
				 * 使​用​标​题​编​号
				 */
				name: string
				/**
				 * 启​用​或​禁​用​在​目​录​中​使​用​标​题​编​号
				 */
				desc: string
			}
			skipHeading1: {
				/**
				 * 跳​过​一​级​标​题
				 */
				name: string
				/**
				 * 启​用​或​禁​用​在​目​录​中​跳​过​一​级​标​题
				 */
				desc: string
			}
			renderMarkdown: {
				/**
				 * 渲​染​ ​M​a​r​k​d​o​w​n
				 */
				name: string
				/**
				 * 启​用​或​禁​用​在​目​录​中​渲​染​ ​M​a​r​k​d​o​w​n
				 */
				desc: string
			}
			showWhenSingleHeading: {
				/**
				 * 单​一​标​题​时​显​示​目​录
				 */
				name: string
				/**
				 * 启​用​或​禁​用​在​文​档​仅​有​单​一​标​题​时​显​示​目​录
				 */
				desc: string
			}
			hideHeadingNumberBlacklist: {
				/**
				 * 标​题​编​号​黑​名​单
				 */
				name: string
				/**
				 * 指​定​需​要​隐​藏​标​题​编​号​的​文​件​（​每​行​一​个​路​径​）​。​支​持​通​配​符​：​*​ ​(​任​意​字​符​)​，​?​ ​(​单​个​字​符​)​。​仅​在​「​使​用​标​题​编​号​」​开​启​时​生​效​。​示​例​：​f​o​l​d​e​r​/​f​i​l​e​.​m​d​ ​或​ ​*​.​m​d
				 */
				desc: string
			}
		}
		tool: {
			/**
			 * 工​具
			 */
			name: string
			headings: {
				/**
				 * 导​航​按​钮​组
				 */
				returnButtons: string
			}
			useToolbar: {
				/**
				 * 使​用​工​具​栏
				 */
				name: string
				/**
				 * 显​示​带​有​导​航​按​钮​的​工​具​栏
				 */
				desc: string
			}
			showProgressBar: {
				/**
				 * 显​示​进​度​条
				 */
				name: string
				/**
				 * 在​目​录​上​方​显​示​阅​读​进​度
				 */
				desc: string
			}
			showProgressCircle: {
				/**
				 * 显​示​进​度​圆​环
				 */
				name: string
				/**
				 * 在​指​示​器​上​方​显​示​阅​读​进​度​，​即​收​缩​目​录​后
				 */
				desc: string
			}
			returnToCursor: {
				/**
				 * 返​回​光​标
				 */
				name: string
				/**
				 * 返​回​到​上​次​光​标​位​置​的​按​钮​（​仅​在​编​辑​模​式​下​可​用​）
				 */
				desc: string
			}
			returnToTop: {
				/**
				 * 返​回​顶​部
				 */
				name: string
				/**
				 * 返​回​到​文​档​顶​部​的​按​钮
				 */
				desc: string
			}
			returnToBottom: {
				/**
				 * 返​回​底​部
				 */
				name: string
				/**
				 * 返​回​到​文​档​底​部​的​按​钮
				 */
				desc: string
			}
			jumpToNextHeading: {
				/**
				 * 跳​转​到​下​一​个​标​题
				 */
				name: string
				/**
				 * 跳​转​到​下​一​个​标​题​的​按​钮
				 */
				desc: string
			}
			jumpToPrevHeading: {
				/**
				 * 跳​转​到​上​一​个​标​题
				 */
				name: string
				/**
				 * 跳​转​到​上​一​个​标​题​的​按​钮
				 */
				desc: string
			}
		}
	}
	cards: {
		/**
		 * 预​览
		 */
		preview: string
		/**
		 * 属​性
		 */
		property: string
		/**
		 * 基​本​设​置
		 */
		basicSetting: string
		/**
		 * 样​式​设​置
		 */
		styleSetting: string
		readingTimeCard: {
			/**
			 * 阅​读​时​间​卡​片​设​置
			 */
			heading: string
			/**
			 * 标​题
			 */
			title: string
			/**
			 * 每​分​钟​中​文​单​词​数
			 */
			chineseWordsPerMinute: string
			/**
			 * 每​分​钟​英​文​单​词​数
			 */
			englishWordsPerMinute: string
			/**
			 * 阅​读​时​间​前​的​文​本
			 */
			textBefore: string
			/**
			 * 阅​读​时​间​后​的​文​本
			 */
			textAfter: string
			/**
			 * 图​标​名​称​（​来​自​O​b​s​i​d​i​a​n​图​标​集​）
			 */
			iconName: string
			/**
			 * 移​除​代​码​块
			 */
			removeCodeBlocks: string
			/**
			 * 移​除​w​i​k​i​链​接
			 */
			removeWikiLinks: string
			/**
			 * 移​除​图​片​链​接
			 */
			removeImageLinks: string
			/**
			 * 移​除​普​通​链​接
			 */
			removeNormalLinks: string
			/**
			 * 显​示​字​数
			 */
			showWordCount: string
		}
		tableOfContentsCard: {
			/**
			 * 目​录​卡​片​设​置
			 */
			heading: string
			/**
			 * 标​题
			 */
			title: string
			/**
			 * 最​小​标​题​深​度
			 */
			minDepth: string
			/**
			 * 最​大​标​题​深​度
			 */
			maxDepth: string
			/**
			 * 启​用​标​题​重​定​向
			 */
			redirect: string
			/**
			 * 显​示​标​题​编​号
			 */
			showNumbers: string
			/**
			 * 使​目​录​可​折​叠
			 */
			collapsible: string
		}
		styles: {
			/**
			 * 当​前​属​性
			 */
			currentProperties: string
			/**
			 * 添​加​新​属​性
			 */
			addNewProperty: string
			/**
			 * 未​定​义​自​定​义​属​性
			 */
			noneCustomProperty: string
		}
	}
	tools: {
		/**
		 * 固​定​/​取​消​固​定​目​录
		 */
		pinTOC: string
		/**
		 * 更​改​目​录​位​置
		 */
		changePosition: string
		/**
		 * 展​开​/​收​起​目​录​项
		 */
		expandCollapse: string
		/**
		 * 向​左​偏​移
		 */
		leftOffset: string
		/**
		 * 向​右​偏​移
		 */
		rightOffset: string
		/**
		 * 复​制​目​录​到​剪​贴​板
		 */
		copyTOC: string
		/**
		 * 返​回​导​航
		 */
		returnNavigation: string
		/**
		 * 返​回​光​标​位​置
		 */
		returnToCursor: string
		/**
		 * 返​回​顶​部
		 */
		returnToTop: string
		/**
		 * 返​回​底​部
		 */
		returnToBottom: string
		/**
		 * 下​一​个​标​题
		 */
		jumpToNextHeading: string
		/**
		 * 上​一​个​标​题
		 */
		jumpToPrevHeading: string
	}
}

export type TranslationFunctions = {
	commands: {
		/**
		 * 打开目录侧边视图
		 */
		openTocView: () => LocalizedString
		/**
		 * 返回光标位置
		 */
		returnToCursor: () => LocalizedString
		/**
		 * 滚动到顶部
		 */
		scrollToTop: () => LocalizedString
		/**
		 * 滚动到底部
		 */
		scrollToBottom: () => LocalizedString
		/**
		 * 导航到上一个标题
		 */
		navigatePreviousHeading: () => LocalizedString
		/**
		 * 导航到下一个标题
		 */
		navigateNextHeading: () => LocalizedString
		/**
		 * 展开/收起目录
		 */
		tocExpand: () => LocalizedString
		/**
		 * 插入阅读时间卡片
		 */
		insertReadingTimeCard: () => LocalizedString
		/**
		 * 插入目录卡片
		 */
		insertTableOfContentsCard: () => LocalizedString
		/**
		 * 添加/移除当前文件到标题编号黑名单
		 */
		addCurrentFileToHideHeadingNumberBlacklist: () => LocalizedString
		/**
		 * 添加/移除当前文件夹到标题编号黑名单
		 */
		addCurrentFolderToHideHeadingNumberBlacklist: () => LocalizedString
	}
	notices: {
		/**
		 * 已被现有规则覆盖
		 */
		alreadyCovered: () => LocalizedString
		/**
		 * 已添加
		 */
		added: () => LocalizedString
		/**
		 * 已添加，并移除了 {count} 个冗余规则
		 */
		addedAndRemovedRedundant: (arg: { count: number }) => LocalizedString
		/**
		 * 不在黑名单中
		 */
		notInBlacklist: () => LocalizedString
		/**
		 * 已移除
		 */
		removed: () => LocalizedString
		/**
		 * 已被某个规则覆盖，如需移除请手动删除该规则
		 */
		coveredByPattern: () => LocalizedString
	}
	view: {
		/**
		 * 未找到标题，请确保当前文档包含标题，或者激活markdown文档视图。
		 */
		view_empty: () => LocalizedString
	}
	settings: {
		toc: {
			/**
			 * 目录
			 */
			name: () => LocalizedString
			show: {
				/**
				 * 显示目录
				 */
				name: () => LocalizedString
				/**
				 * 启用或禁用目录功能
				 */
				desc: () => LocalizedString
			}
			alwaysExpand: {
				/**
				 * 始终展开目录
				 */
				name: () => LocalizedString
				/**
				 * 启用或禁用始终展开目录，可使用文档属性 `cssclasses` 来控制显示与隐藏：
				 */
				desc: () => LocalizedString
			}
			width: {
				/**
				 * 目录宽度
				 */
				name: () => LocalizedString
				/**
				 * 设置目录的宽度
				 */
				desc: () => LocalizedString
			}
			position: {
				/**
				 * 目录位置
				 */
				name: () => LocalizedString
				/**
				 * 设置目录的位置
				 */
				desc: () => LocalizedString
				options: {
					/**
					 * 左侧
					 */
					left: () => LocalizedString
					/**
					 * 右侧
					 */
					right: () => LocalizedString
				}
			}
			offset: {
				/**
				 * 目录偏移
				 */
				name: () => LocalizedString
				/**
				 * 设置目录的偏移量
				 */
				desc: () => LocalizedString
			}
		}
		render: {
			/**
			 * 渲染
			 */
			name: () => LocalizedString
			useHeadingNumber: {
				/**
				 * 使用标题编号
				 */
				name: () => LocalizedString
				/**
				 * 启用或禁用在目录中使用标题编号
				 */
				desc: () => LocalizedString
			}
			skipHeading1: {
				/**
				 * 跳过一级标题
				 */
				name: () => LocalizedString
				/**
				 * 启用或禁用在目录中跳过一级标题
				 */
				desc: () => LocalizedString
			}
			renderMarkdown: {
				/**
				 * 渲染 Markdown
				 */
				name: () => LocalizedString
				/**
				 * 启用或禁用在目录中渲染 Markdown
				 */
				desc: () => LocalizedString
			}
			showWhenSingleHeading: {
				/**
				 * 单一标题时显示目录
				 */
				name: () => LocalizedString
				/**
				 * 启用或禁用在文档仅有单一标题时显示目录
				 */
				desc: () => LocalizedString
			}
			hideHeadingNumberBlacklist: {
				/**
				 * 标题编号黑名单
				 */
				name: () => LocalizedString
				/**
				 * 指定需要隐藏标题编号的文件（每行一个路径）。支持通配符：* (任意字符)，? (单个字符)。仅在「使用标题编号」开启时生效。示例：folder/file.md 或 *.md
				 */
				desc: () => LocalizedString
			}
		}
		tool: {
			/**
			 * 工具
			 */
			name: () => LocalizedString
			headings: {
				/**
				 * 导航按钮组
				 */
				returnButtons: () => LocalizedString
			}
			useToolbar: {
				/**
				 * 使用工具栏
				 */
				name: () => LocalizedString
				/**
				 * 显示带有导航按钮的工具栏
				 */
				desc: () => LocalizedString
			}
			showProgressBar: {
				/**
				 * 显示进度条
				 */
				name: () => LocalizedString
				/**
				 * 在目录上方显示阅读进度
				 */
				desc: () => LocalizedString
			}
			showProgressCircle: {
				/**
				 * 显示进度圆环
				 */
				name: () => LocalizedString
				/**
				 * 在指示器上方显示阅读进度，即收缩目录后
				 */
				desc: () => LocalizedString
			}
			returnToCursor: {
				/**
				 * 返回光标
				 */
				name: () => LocalizedString
				/**
				 * 返回到上次光标位置的按钮（仅在编辑模式下可用）
				 */
				desc: () => LocalizedString
			}
			returnToTop: {
				/**
				 * 返回顶部
				 */
				name: () => LocalizedString
				/**
				 * 返回到文档顶部的按钮
				 */
				desc: () => LocalizedString
			}
			returnToBottom: {
				/**
				 * 返回底部
				 */
				name: () => LocalizedString
				/**
				 * 返回到文档底部的按钮
				 */
				desc: () => LocalizedString
			}
			jumpToNextHeading: {
				/**
				 * 跳转到下一个标题
				 */
				name: () => LocalizedString
				/**
				 * 跳转到下一个标题的按钮
				 */
				desc: () => LocalizedString
			}
			jumpToPrevHeading: {
				/**
				 * 跳转到上一个标题
				 */
				name: () => LocalizedString
				/**
				 * 跳转到上一个标题的按钮
				 */
				desc: () => LocalizedString
			}
		}
	}
	cards: {
		/**
		 * 预览
		 */
		preview: () => LocalizedString
		/**
		 * 属性
		 */
		property: () => LocalizedString
		/**
		 * 基本设置
		 */
		basicSetting: () => LocalizedString
		/**
		 * 样式设置
		 */
		styleSetting: () => LocalizedString
		readingTimeCard: {
			/**
			 * 阅读时间卡片设置
			 */
			heading: () => LocalizedString
			/**
			 * 标题
			 */
			title: () => LocalizedString
			/**
			 * 每分钟中文单词数
			 */
			chineseWordsPerMinute: () => LocalizedString
			/**
			 * 每分钟英文单词数
			 */
			englishWordsPerMinute: () => LocalizedString
			/**
			 * 阅读时间前的文本
			 */
			textBefore: () => LocalizedString
			/**
			 * 阅读时间后的文本
			 */
			textAfter: () => LocalizedString
			/**
			 * 图标名称（来自Obsidian图标集）
			 */
			iconName: () => LocalizedString
			/**
			 * 移除代码块
			 */
			removeCodeBlocks: () => LocalizedString
			/**
			 * 移除wiki链接
			 */
			removeWikiLinks: () => LocalizedString
			/**
			 * 移除图片链接
			 */
			removeImageLinks: () => LocalizedString
			/**
			 * 移除普通链接
			 */
			removeNormalLinks: () => LocalizedString
			/**
			 * 显示字数
			 */
			showWordCount: () => LocalizedString
		}
		tableOfContentsCard: {
			/**
			 * 目录卡片设置
			 */
			heading: () => LocalizedString
			/**
			 * 标题
			 */
			title: () => LocalizedString
			/**
			 * 最小标题深度
			 */
			minDepth: () => LocalizedString
			/**
			 * 最大标题深度
			 */
			maxDepth: () => LocalizedString
			/**
			 * 启用标题重定向
			 */
			redirect: () => LocalizedString
			/**
			 * 显示标题编号
			 */
			showNumbers: () => LocalizedString
			/**
			 * 使目录可折叠
			 */
			collapsible: () => LocalizedString
		}
		styles: {
			/**
			 * 当前属性
			 */
			currentProperties: () => LocalizedString
			/**
			 * 添加新属性
			 */
			addNewProperty: () => LocalizedString
			/**
			 * 未定义自定义属性
			 */
			noneCustomProperty: () => LocalizedString
		}
	}
	tools: {
		/**
		 * 固定/取消固定目录
		 */
		pinTOC: () => LocalizedString
		/**
		 * 更改目录位置
		 */
		changePosition: () => LocalizedString
		/**
		 * 展开/收起目录项
		 */
		expandCollapse: () => LocalizedString
		/**
		 * 向左偏移
		 */
		leftOffset: () => LocalizedString
		/**
		 * 向右偏移
		 */
		rightOffset: () => LocalizedString
		/**
		 * 复制目录到剪贴板
		 */
		copyTOC: () => LocalizedString
		/**
		 * 返回导航
		 */
		returnNavigation: () => LocalizedString
		/**
		 * 返回光标位置
		 */
		returnToCursor: () => LocalizedString
		/**
		 * 返回顶部
		 */
		returnToTop: () => LocalizedString
		/**
		 * 返回底部
		 */
		returnToBottom: () => LocalizedString
		/**
		 * 下一个标题
		 */
		jumpToNextHeading: () => LocalizedString
		/**
		 * 上一个标题
		 */
		jumpToPrevHeading: () => LocalizedString
	}
}

export type Formatters = {}
